export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_PROFILE = 'SIGN_IN_PROFILE';
export const SET_CURRENT_FRIEND = 'SET_CURRENT_FRIEND';
export const SET_CONTACTS_OVERVIEW_MESSAGES = 'SET_CONTACTS_OVERVIEW_MESSAGES';
export const SET_CONTACTS_OVERVIEW_MESSAGES_COUNT = 'SET_CONTACTS_OVERVIEW_MESSAGES_COUNT';
export const SET_CONTACTS_OVERVIEW_MESSAGES_COUNT_UNREAD = 'SET_CONTACTS_OVERVIEW_MESSAGES_COUNT'
export const SET_USER_DATA = 'SET_USER_DATA'
